name: picencrypt
description: "PicEncrypt flutter project"
repository: https://github.com/huedevwork/picencrypt

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# 1.0.0 versionName. 1 versionCode
version: 1.0.2+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: any
  get_storage: any
  image: any
  path: any
  path_provider: any
  image_picker: any
  file_picker: any
  window_manager: any
  flutter_easyloading: any
  isolate: any
  intl: any
  permission_handler: any
  auto_size_text: any
  url_launcher: any
  package_info_plus: any
  device_info_plus: any
  photo_view: any
  uuid: any
  mime: any
  logger: any

  picencrypt_converter:
    path: package/picencrypt_converter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # dart run build_runner build
  flutter_gen_runner: any
  build_runner: any

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
