name: picencrypt_converter
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  image: any
  crypto: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
